// Code generated by ogen, DO NOT EDIT.

package mediamtx

// ConfigPathsAddParams is parameters of configPathsAdd operation.
type ConfigPathsAddParams struct {
	// The name of the path.
	Name string
}

// ConfigPathsDeleteParams is parameters of configPathsDelete operation.
type ConfigPathsDeleteParams struct {
	// The name of the path.
	Name string
}

// ConfigPathsGetParams is parameters of configPathsGet operation.
type ConfigPathsGetParams struct {
	// The name of the path.
	Name string
}

// ConfigPathsListParams is parameters of configPathsList operation.
type ConfigPathsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// ConfigPathsPatchParams is parameters of configPathsPatch operation.
type ConfigPathsPatchParams struct {
	// The name of the path.
	Name string
}

// ConfigPathsReplaceParams is parameters of configPathsReplace operation.
type ConfigPathsReplaceParams struct {
	// The name of the path.
	Name string
}

// HlsMuxersGetParams is parameters of hlsMuxersGet operation.
type HlsMuxersGetParams struct {
	// Name of the muxer.
	Name string
}

// HlsMuxersListParams is parameters of hlsMuxersList operation.
type HlsMuxersListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// PathsGetParams is parameters of pathsGet operation.
type PathsGetParams struct {
	// Name of the path.
	Name string
}

// PathsListParams is parameters of pathsList operation.
type PathsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// RecordingsDeleteSegmentParams is parameters of recordingsDeleteSegment operation.
type RecordingsDeleteSegmentParams struct {
	// Path.
	Path string
	// Starting date of the segment.
	Start string
}

// RecordingsGetParams is parameters of recordingsGet operation.
type RecordingsGetParams struct {
	// Name of the path.
	Name string
}

// RecordingsListParams is parameters of recordingsList operation.
type RecordingsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// RtmpConnectionsGetParams is parameters of rtmpConnectionsGet operation.
type RtmpConnectionsGetParams struct {
	// ID of the connection.
	ID string
}

// RtmpConnsKickParams is parameters of rtmpConnsKick operation.
type RtmpConnsKickParams struct {
	// ID of the connection.
	ID string
}

// RtmpConnsListParams is parameters of rtmpConnsList operation.
type RtmpConnsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// RtmpsConnectionsGetParams is parameters of rtmpsConnectionsGet operation.
type RtmpsConnectionsGetParams struct {
	// ID of the connection.
	ID string
}

// RtmpsConnsKickParams is parameters of rtmpsConnsKick operation.
type RtmpsConnsKickParams struct {
	// ID of the connection.
	ID string
}

// RtmpsConnsListParams is parameters of rtmpsConnsList operation.
type RtmpsConnsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// RtspConnsGetParams is parameters of rtspConnsGet operation.
type RtspConnsGetParams struct {
	// ID of the connection.
	ID string
}

// RtspConnsListParams is parameters of rtspConnsList operation.
type RtspConnsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// RtspSessionsGetParams is parameters of rtspSessionsGet operation.
type RtspSessionsGetParams struct {
	// ID of the connection.
	ID string
}

// RtspSessionsKickParams is parameters of rtspSessionsKick operation.
type RtspSessionsKickParams struct {
	// ID of the session.
	ID string
}

// RtspSessionsListParams is parameters of rtspSessionsList operation.
type RtspSessionsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// RtspsConnsGetParams is parameters of rtspsConnsGet operation.
type RtspsConnsGetParams struct {
	// ID of the connection.
	ID string
}

// RtspsConnsListParams is parameters of rtspsConnsList operation.
type RtspsConnsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// RtspsSessionsGetParams is parameters of rtspsSessionsGet operation.
type RtspsSessionsGetParams struct {
	// ID of the connection.
	ID string
}

// RtspsSessionsKickParams is parameters of rtspsSessionsKick operation.
type RtspsSessionsKickParams struct {
	// ID of the session.
	ID string
}

// RtspsSessionsListParams is parameters of rtspsSessionsList operation.
type RtspsSessionsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// SrtConnsGetParams is parameters of srtConnsGet operation.
type SrtConnsGetParams struct {
	// ID of the connection.
	ID string
}

// SrtConnsKickParams is parameters of srtConnsKick operation.
type SrtConnsKickParams struct {
	// ID of the connection.
	ID string
}

// SrtConnsListParams is parameters of srtConnsList operation.
type SrtConnsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}

// WebrtcSessionsGetParams is parameters of webrtcSessionsGet operation.
type WebrtcSessionsGetParams struct {
	// ID of the session.
	ID string
}

// WebrtcSessionsKickParams is parameters of webrtcSessionsKick operation.
type WebrtcSessionsKickParams struct {
	// ID of the session.
	ID string
}

// WebrtcSessionsListParams is parameters of webrtcSessionsList operation.
type WebrtcSessionsListParams struct {
	// Page number.
	Page OptInt
	// Items per page.
	ItemsPerPage OptInt
}
