// Code generated by ogen, DO NOT EDIT.

package mediamtx

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthJwksRefreshOperation         OperationName = "AuthJwksRefresh"
	ConfigGlobalGetOperation         OperationName = "ConfigGlobalGet"
	ConfigGlobalSetOperation         OperationName = "ConfigGlobalSet"
	ConfigPathDefaultsGetOperation   OperationName = "ConfigPathDefaultsGet"
	ConfigPathDefaultsPatchOperation OperationName = "ConfigPathDefaultsPatch"
	ConfigPathsAddOperation          OperationName = "ConfigPathsAdd"
	ConfigPathsDeleteOperation       OperationName = "ConfigPathsDelete"
	ConfigPathsGetOperation          OperationName = "ConfigPathsGet"
	ConfigPathsListOperation         OperationName = "ConfigPathsList"
	ConfigPathsPatchOperation        OperationName = "ConfigPathsPatch"
	ConfigPathsReplaceOperation      OperationName = "ConfigPathsReplace"
	HlsMuxersGetOperation            OperationName = "HlsMuxersGet"
	HlsMuxersListOperation           OperationName = "HlsMuxersList"
	PathsGetOperation                OperationName = "PathsGet"
	PathsListOperation               OperationName = "PathsList"
	RecordingsDeleteSegmentOperation OperationName = "RecordingsDeleteSegment"
	RecordingsGetOperation           OperationName = "RecordingsGet"
	RecordingsListOperation          OperationName = "RecordingsList"
	RtmpConnectionsGetOperation      OperationName = "RtmpConnectionsGet"
	RtmpConnsKickOperation           OperationName = "RtmpConnsKick"
	RtmpConnsListOperation           OperationName = "RtmpConnsList"
	RtmpsConnectionsGetOperation     OperationName = "RtmpsConnectionsGet"
	RtmpsConnsKickOperation          OperationName = "RtmpsConnsKick"
	RtmpsConnsListOperation          OperationName = "RtmpsConnsList"
	RtspConnsGetOperation            OperationName = "RtspConnsGet"
	RtspConnsListOperation           OperationName = "RtspConnsList"
	RtspSessionsGetOperation         OperationName = "RtspSessionsGet"
	RtspSessionsKickOperation        OperationName = "RtspSessionsKick"
	RtspSessionsListOperation        OperationName = "RtspSessionsList"
	RtspsConnsGetOperation           OperationName = "RtspsConnsGet"
	RtspsConnsListOperation          OperationName = "RtspsConnsList"
	RtspsSessionsGetOperation        OperationName = "RtspsSessionsGet"
	RtspsSessionsKickOperation       OperationName = "RtspsSessionsKick"
	RtspsSessionsListOperation       OperationName = "RtspsSessionsList"
	SrtConnsGetOperation             OperationName = "SrtConnsGet"
	SrtConnsKickOperation            OperationName = "SrtConnsKick"
	SrtConnsListOperation            OperationName = "SrtConnsList"
	WebrtcSessionsGetOperation       OperationName = "WebrtcSessionsGet"
	WebrtcSessionsKickOperation      OperationName = "WebrtcSessionsKick"
	WebrtcSessionsListOperation      OperationName = "WebrtcSessionsList"
)
