// Code generated by ogen, DO NOT EDIT.
package mediamtx

type AuthJwksRefreshRes interface {
	authJwksRefreshRes()
}

type ConfigGlobalGetRes interface {
	configGlobalGetRes()
}

type ConfigGlobalSetRes interface {
	configGlobalSetRes()
}

type ConfigPathDefaultsGetRes interface {
	configPathDefaultsGetRes()
}

type ConfigPathDefaultsPatchRes interface {
	configPathDefaultsPatchRes()
}

type ConfigPathsAddRes interface {
	configPathsAddRes()
}

type ConfigPathsDeleteRes interface {
	configPathsDeleteRes()
}

type ConfigPathsGetRes interface {
	configPathsGetRes()
}

type ConfigPathsListRes interface {
	configPathsListRes()
}

type ConfigPathsPatchRes interface {
	configPathsPatchRes()
}

type ConfigPathsReplaceRes interface {
	configPathsReplaceRes()
}

type HlsMuxersGetRes interface {
	hlsMuxersGetRes()
}

type HlsMuxersListRes interface {
	hlsMuxersListRes()
}

type PathsGetRes interface {
	pathsGetRes()
}

type PathsListRes interface {
	pathsListRes()
}

type RecordingsDeleteSegmentRes interface {
	recordingsDeleteSegmentRes()
}

type RecordingsGetRes interface {
	recordingsGetRes()
}

type RecordingsListRes interface {
	recordingsListRes()
}

type RtmpConnectionsGetRes interface {
	rtmpConnectionsGetRes()
}

type RtmpConnsKickRes interface {
	rtmpConnsKickRes()
}

type RtmpConnsListRes interface {
	rtmpConnsListRes()
}

type RtmpsConnectionsGetRes interface {
	rtmpsConnectionsGetRes()
}

type RtmpsConnsKickRes interface {
	rtmpsConnsKickRes()
}

type RtmpsConnsListRes interface {
	rtmpsConnsListRes()
}

type RtspConnsGetRes interface {
	rtspConnsGetRes()
}

type RtspConnsListRes interface {
	rtspConnsListRes()
}

type RtspSessionsGetRes interface {
	rtspSessionsGetRes()
}

type RtspSessionsKickRes interface {
	rtspSessionsKickRes()
}

type RtspSessionsListRes interface {
	rtspSessionsListRes()
}

type RtspsConnsGetRes interface {
	rtspsConnsGetRes()
}

type RtspsConnsListRes interface {
	rtspsConnsListRes()
}

type RtspsSessionsGetRes interface {
	rtspsSessionsGetRes()
}

type RtspsSessionsKickRes interface {
	rtspsSessionsKickRes()
}

type RtspsSessionsListRes interface {
	rtspsSessionsListRes()
}

type SrtConnsGetRes interface {
	srtConnsGetRes()
}

type SrtConnsKickRes interface {
	srtConnsKickRes()
}

type SrtConnsListRes interface {
	srtConnsListRes()
}

type WebrtcSessionsGetRes interface {
	webrtcSessionsGetRes()
}

type WebrtcSessionsKickRes interface {
	webrtcSessionsKickRes()
}

type WebrtcSessionsListRes interface {
	webrtcSessionsListRes()
}
